services:
  pg_db:
    image: postgres:10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/kohada/de-zoomcamp/data/ny_taxi_postgres_data:/var/lib/postgresql/taxi_data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home/kohada/de-zoomcamp/data/pgadmin_config:/var/lib/pgadmin:rw"
    ports:
      - "8080:80"